name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  LLVM_PROFILE_FILE: "bo-%p-%m.profraw"
  RUSTFLAGS: "-Cinstrument-coverage"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: rustup component add llvm-tools-preview && cargo install grcov
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run coverage
        run:  grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o lcov.info
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          file: lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: doanthaibao/rust_string_utils
      - name: Release to crates
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --verbose

